[toolchain]
channel = "1.80.1"
components = [
  "clippy",
  "rustfmt",
  "rust-analyzer",
  "rust-src"
]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-gnu"
]

[profile.release]
opt-level = 3
