[package]
name = "kickbase"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
server = { path = "../server" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
