[package]
name = "kickbase"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
server.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
workspace = { version = "0.1", path = "../workspace" }
